server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update   # change to validate in prod
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: sentientgate-logging-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 500

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "edu.pict.loggingservice.kafka.model"

    listener:
      concurrency: 3
      type: batch
      ack-mode: batch
