spring.application.name=eureka-server


# Do NOT register Eureka server as a client

eureka.client.register-with-eureka=false

# Do NOT fetch registry

eureka.client.fetch-registry=false

# IMPORTANT: Plain URL only (NO brackets)

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Instance settings

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true

# Server behavior

server.port=8761

eureka.server.enable-self-preservation=true
eureka.server.eviction-interval-timer-in-ms=60000

spring.output.ansi.enabled=always