spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: after_route
              uri: lb://DUMMYSERVICE
              predicates:
                - Path=/dummy/**
            - id: logging_service
              uri: lb://LOGGINGSERVICE
              predicates:
                - Path=/loggingService/**
#              order=100
#              predicates:
#                - Cookie=mycookie,mycookievalue
#            - id: user-service
#              uri: lb://DUMMYSERVICE
#              predicates:

#                - Path=/api/v1/inventory/**
#              filters:
#                - StripPrefix=2


  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


    properties:
      spring.json.trusted.packages: "edu.pict.apigateway.kafkaEvent"


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
