spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: after_route
              uri: https://example.org
              predicates:
              - Cookie=mycookie,mycookievalue
            - id: user-service
              uri: lb://DUMMYSERVICE
              predicates:

#                - Path=/api/v1/inventory/**
#              filters:
#                - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
