apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-server-config
  namespace: sentientgate
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka"
  GRPC_CLIENT_LOGGING_SERVICE_ADDRESS: "discovery:///LOGGING-SERVICE"
  SERVER_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server
  namespace: sentientgate
  labels:
    app: mcp-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mcp-server
  template:
    metadata:
      labels:
        app: mcp-server
    spec:
      containers:
        - name: mcp-server
          image: shrihari7396/mcp-server:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: mcp-server-config
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  namespace: sentientgate
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: mcp-server
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mcp-server-hpa
  namespace: sentientgate
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mcp-server
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
