spring:
  application:
    name: dummy-service
server:
  port: 8090
#  servlet:
#    context-path: /dummy/


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true