apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/mydb"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka"
  SERVER_PORT: "8080"
