apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-service
  labels:
    app: logging-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging-service
  template:
    metadata:
      labels:
        app: logging-service
    spec:
      containers:
        - name: logging-service
          image: shrihari7396/logging-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: logging-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: logging-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logging-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: logging-config
                  key: SPRING_KAFKA_BOOTSTRAP_SERVERS
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: logging-config
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: logging-config
                  key: SERVER_PORT
          ports:
            - name: http
              containerPort: 8080
            - name: grpc
              containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: logging-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 9090
      targetPort: 9090
  selector:
    app: logging-service
