apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  SPRING_DATA_REDIS_HOST: "redis"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service:29092"
  SERVER_PORT: "8080"
