apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-server-config
data:
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka"
  GRPC_CLIENT_LOGGING_SERVICE_ADDRESS: "discovery:///LOGGING-SERVICE"
  SERVER_PORT: "8080"
