server:
  port: 8010
  servlet:
    context-path: /logging-service

spring:
  output:
    ansi:
      enabled: always
  application:
    name: logging-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update   # change to validate in prod
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: sentientgate-logging-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 500

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: true
        spring.json.type.mapping: "edu.pict.apigateway.kafkaEvent.LogEvent:edu.pict.loggingservice.kafka.model.GatewayDecisionEvent"

    listener:
      concurrency: 3
      type: batch
      ack-mode: batch

  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    metadata-map:
      gRPC.port: 9090
