server:
  port: 9991
  servlet:
    context-path: /mcp-service

#spring:
#  redis:
#    host: localhost
#    port: 6379
spring:
  application:
    name: mcp-server
  output:
    ansi:
      enabled: always
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: sentientgate-mcp-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 500

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: true
        spring.json.type.mapping: "edu.pict.apigateway.kafkaEvent.SecurityAlertEvent:edu.pict.mcpservice.kafkaEvents.SecurityAlertEvent,edu.pict.apigateway.kafkaEvent.LogEvent:edu.pict.mcpservice.kafkaEvents.LogEvent"

    listener:
      concurrency: 3
      type: batch
      ack-mode: batch

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

grpc:
  client:
    logging-service:
      address: discovery:///LOGGING-SERVICE
      negotiation-type: plaintext