apiVersion: v1 # Specifies the Kubernetes API version for this resource
kind: PersistentVolumeClaim # Declares the resource type as a PersistentVolumeClaim
metadata: # Contains metadata parameters for identifying the resource
  name: postgres-pvc # Unique name of the PersistentVolumeClaim in the namespace
spec: # Details the desired characteristics and specifications of the volume
  accessModes: # Lists the access permissions required for the volume
    - ReadWriteOnce # Indicates the volume can be mounted as read-write by a single node
  resources: # Defines the resource requests and limits for the volume
    requests: # Specifies the minimum resource requests
      storage: 1Gi # Requests 1 Gigabyte of persistent storage capacity
