apiVersion: v1 # Specifies the Kubernetes API version for this resource
kind: Secret # Declares the resource type as a Secret for sensitive data
metadata: # Contains metadata parameters for identifying the resource
  name: postgres-secret # Unique name of the Secret in the namespace
type: Opaque # Indicates the secret contains arbitrary user-defined data
data: # Holds the sensitive data key-value pairs (must be base64 encoded)
  POSTGRES_USER: cG9zdGdyZXM= # Base64 encoded value for 'postgres' username
  POSTGRES_PASSWORD: cG9zdGdyZXM= # Base64 encoded value for 'postgres' password
